version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "8000"
      DEBUG: "true"
      SECRET_KEY: "your_secret_key_here"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      MODEL_API_KEY: "${MODEL_API_KEY}"
      MODEL_API_URL: "${MODEL_API_URL}"
      DB_ENGINE: "${DB_ENGINE}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      REDIS_URL: "redis://redis:6379"
    volumes:
      - ./src:/usr/src/app
    networks:
      - nao-ai-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nao-ai-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - nao-ai-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nao-ai-network

volumes:
  postgres_data:

networks:
  nao-ai-network:
    driver: bridge
