services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    depends_on:
      - postgres
    environment:
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "8000"
      DEBUG: "true"
      SECRET_KEY: "your_secret_key_here"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"  # Load from .env
      DB_ENGINE: "${DB_ENGINE}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      # Add more variables as necessary

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
