apiVersion: v1
kind: Config
metadata:
  name: google-ads-config
data:
  projectId: your-project-id
  developer_token: 'INSERT_DEVELOPER_TOKEN_HERE'
  client_id: 'INSERT_CLIENT_ID_HERE'
  client_secret: 'INSERT_CLIENT_SECRET_HERE'
  refresh_token: 'INSERT_REFRESH_TOKEN_HERE'
  login_customer_id: 'INSERT_LOGIN_CUSTOMER_ID_HERE'
