apiVersion: apps/v1
kind: Deployment
metadata:
  name: ali1ion-deployment
  labels:
    app: ali1ion
  annotations:
    description: "Deployment for Ali1ion module"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ali1ion
  template:
    metadata:
      labels:
        app: ali1ion
    spec:
      containers:
      - name: ali1ion-container
        image: gcr.io/your-project-id/ali1ion-module:latest
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: APP_NAME
          value: "Ali1ion"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        volumeMounts:
        - name: ali1ion-config
          mountPath: /etc/config
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: ali1ion-config
        configMap:
          name: ali1ion-config
