apiVersion: v1
kind: Service
metadata:
  name: ali1ion-service
  labels:
    app: ali1ion
spec:
  selector:
    app: ali1ion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
