# k8s_config

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ali1ion-deployment
  labels:
    app: ali1ion
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ali1ion
  template:
    metadata:
      labels:
        app: ali1ion
    spec:
      containers:
      - name: ali1ion-container
        image: gcr.io/ali1ion-project/ali1ion-node-app:latest
        ports:
        - containerPort: 7860
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: ali1ion-service
spec:
  selector:
    app: ali1ion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7860
  type: LoadBalancer
