swagger: "2.0"
info:
  title: NAO-AI API
  description: API for NAO-AI services
  version: "1.0.0"
paths:
  /:
    get:
      summary: Root endpoint
      operationId: getRoot
      responses:
        200:
          description: A successful response
          schema:
            type: string
            example: Hello World!
      x-google-backend:
        address: https://your-backend-url  # Replace with your actual backend URL
  /status:
    get:
      summary: Get the status of the NAO-AI module
      operationId: getStatus
      responses:
        200:
          description: A successful response
          schema:
            type: object
            properties:
              status:
                type: string
                example: running
      x-google-backend:
        address: https://your-backend-url/status  # Replace with your actual backend URL
  /predict:
    post:
      summary: Get predictions from the NAO-AI module
      operationId: getPredictions
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: input
          description: Input data for prediction
          required: true
          schema:
            type: object
            properties:
              input_data:
                type: array
                items:
                  type: string
                example: ["data1", "data2"]
      responses:
        200:
          description: A successful response
          schema:
            type: object
            properties:
              predictions:
                type: array
                items:
                  type: string
                example: ["prediction1", "prediction2"]
        400:
          description: Invalid input data
        500:
          description: Internal server error
      x-google-backend:
        address: https://your-backend-url/predict  # Replace with your actual backend URL
